version: '3.9'

services:
  frontend:
    build:
      context: ../../../electroneum-sc-block-explorer-frontend
      dockerfile: Dockerfile
    image: frontend
    pull_policy: never
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
