version: '3.8'

services:
  blockscout:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      MIX_ENV: dev # Sets the environment to dev, enabling Phoenix’s hot-reloading.
    volumes:
      - ../apps:/opt/app/apps # Map the local Blockscout codebase into the container
      - ../config:/opt/app/config # If you also want to tweak config files
      - ../envs:/envs # Map the env files for easier editing
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    ports:
      - 4000:4000 # Phoenix app
      - 4001:4001 # Optional debugger port
